### ISSUE TITLE
Demo link goes to docs, not showing a demo 

### ISSUE THREAD

**Issue by michabbb** [Xammie/mailbook#81]
https://github.com/Xammie/mailbook/blob/825ddd7f09d5f08b9a314a92d2e421cde97683b1/README.md?plain=1#L13

**Comment by Xammie** [comment]
This is intended as the demo shows the readme as the default selected mail.

**Comment by BartvanS** [comment]
@michabbb, chill. It is an open source project. If something is not working correctly you can ofcourse always create a issue or better yet: create a pull request! There is no need to have this attitude for free.

**Comment by Xammie** [comment]
@michabbb You've probably opened the link on your phone which is why you are confusing the demo with docs. If you would open the link on your desktop you will see that it is in fact a demo site. 

If you are having a different issue I would really appreciate some more information about what is not working next time. Opening an issue with this little information makes it difficult for me to help you.

I don't appreciate your sarcastic comment. Let me remind you that I do this open-source work for free. Let's strive for mutual respect and constructive feedback.

**Comment by michabbb** [comment]
I opened it on my mobile. On the desktop, I can see what you explained. Thanks for the not-so-unimportant information, and I wish you a happy, non-sarcastic week.
